### ISSUE TITLE
1.3-alpine is not being updated to with the 1.3.x updates

### ISSUE THREAD

**Issue by nhaugo** [influxdata/influxdata-docker#130]

**Comment by jsternberg** [comment]
I just pulled the latest `chronograf:1.3-alpine` and ran it to get this:

```
$ docker run --rm chronograf:1.3-alpine -v
2017/08/31 04:11:19 Chronograf 1.3.7.0 (git: a9358a3dcbc1e74533a888435719d440884d806e)
```

Is that incorrect? It looks like the correct version to me.

**Comment by nhaugo** [comment]
Ok, i figured the image would have the same image id as 1.3.7.0, but you are right this looks good.

Thanks
