### ISSUE TITLE
Telegraf 1.4.1-alpine statsd issues

### ISSUE THREAD

**Issue by antstorm** [influxdata/influxdata-docker#153]
Hi,

It seems like the `1.4.1-alpine` would not accept any calls to statsd plugin from the host. The same call works fine when executed from within the container itself: `echo "a_counter:10|c" | nc -w0 -u 127.0.0.1 8125`.

This works perfectly fine on `1.4.1` using exactly the same configuration.

**Comment by jsternberg** [comment]
Does this happen for the 1.3 image too? I'm guessing that some piece of software is needed for statsd that's not in the alpine image.

**Comment by danielnelson** [comment]
I'm going to close this issue due to age, but let me know if it is still occuring.
