### ISSUE TITLE
can't get https to work

### ISSUE THREAD

**Issue by joliveros** [influxdata/influxdata-docker#157]
Could it be due to this line?
https://github.com/influxdata/influxdata-docker/blob/fa56c091ebf85652d3f41a72cf058298d59cc66e/influxdb/1.3/init-influxdb.sh#L35

**Comment by jsternberg** [comment]
That only affects the initialization.

Can you give me more details on what you have done and what errors you are getting?

**Comment by wbaker85** [comment]
Going to close this since it has had a very long period of inactivity. I'd suggest checking out the docs at https://docs.influxdata.com/influxdb/v2.1/security/enable-tls/ for more info on enabling TLS.
