### ISSUE TITLE
"This image has vulnerabilities"

### ISSUE THREAD

**Issue by mvhconsult** [influxdata/influxdata-docker#171]
https://hub.docker.com/r/library/influxdb/tags/
Nearly all tagged imags have warnings, some red. 

Probably because there is no apk update && apk upgrade for Alpine
https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management

**Comment by jsternberg** [comment]
It looks like it displays warnings for every single image layer and some of the most egregious warnings are from the base images that we use. I'll take a look at it and see if we can fix those.

**Comment by wbaker85** [comment]
I took a quick look at our ~recent images on docker hub and they do not appear to have warnings anymore, so I'm closing this!
