### ISSUE TITLE
Continuous CPU usage on Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by alexdrl** [influxdata/influxdata-docker#194]
Hello, I am seeing a continous high CPU usage running this container on a Raspberry Pi 3

![image](https://user-images.githubusercontent.com/26382633/36441918-5b335232-1674-11e8-8f40-957d358378a9.png)

I am hosting grafana, influxdb and home-assistant here. I have noticed this when I started to get monitoring from this containers using telegraf.

I have tried to stop grafana and home-assistant, and the spikes of CPU usage continue. What can I do?

**Comment by morganics** [comment]
I'd suggest checking the logs; `docker logs <containername> --tail 1000`. I recently found that a low ulimit was causing high CPU usage, so I just opened an issue, which might be of some help: https://github.com/influxdata/influxdata-docker/issues/204

**Comment by alexdrl** [comment]
@morganics I don't see anything related to 'ulimit' in the logs. I opened a issue on the more global GitHub repo about this, with logs.

**Comment by alexdrl** [comment]
Closed as of https://github.com/influxdata/influxdb/issues/9475#issuecomment-375888132
