### ISSUE TITLE
telegraf inside docker 

### ISSUE THREAD

**Issue by kingsqv** [influxdata/influxdata-docker#210]
If i install telegraf use docker , how to monitor cpu ，mem on the host

**Comment by matjazmav** [comment]
+1

**Comment by cuipito** [comment]
You can use the docker telegraf plugin.
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker

And us a query like this.

SELECT mean("usage_percent") AS "mean_usage_percent" FROM "telegraf"."autogen"."docker_container_cpu_docker" WHERE time > :dashboardTime: AND "engine_host"='name-of-your-host' GROUP BY time(:interval:) FILL(null)

**Comment by jsternberg** [comment]
Done.

docker-library/docs#1216
