### ISSUE TITLE
cannot use arguments via ansible

### ISSUE THREAD

**Issue by ChrisLMerrill** [influxdata/influxdata-docker#219]
When starting the container via ansible, there is no facility to pass command-line arguments. Thus, starting Chronograf and passing the InfluxDB URL as shown in the example is not possible. Specifically, there is no way do this from Ansible:
  docker run -p 8888:8888 --net=influxdb chronograf --influxdb-url=http://influxdb:8086
Everything but the --influxdb-url parameter works.

Would it be possible to expose this in an environment variable instead?

(as an example, the INFLUXDB_GRAPHITE_ENABLED=true env variable works great when starting the InfluxDB container via ansible)

**Comment by jsternberg** [comment]
I think this is what you're looking for: https://docs.influxdata.com/chronograf/v1.4/administration/config-options

Just look at the environment variables for each option.
