### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by dandv** [influxdata/influxdata-docker#22]
Maybe with contents from https://hub.docker.com/_/influxdb/ ?

New users might want to know details about this image, such as the ports, whether SSL is enabled etc.

**Comment by Hipska** [comment]
Each folder for a application/image has its own README file.

**Comment by dandv** [comment]
If after 6 years of deliberation that means there should be no README at the root level, I'll stand rebuked :)

**Comment by Hipska** [comment]
Oh, but you were referring to the readme of InfluxDB.

Anyway, You are free to create a PR that adds a readme file.
