### ISSUE TITLE
Add option to enable HTTPS

### ISSUE THREAD

**Issue by dandv** [influxdata/influxdata-docker#23]
I'm hunting a bug in a Node client library that might be triggered by HTTPS.

**Comment by jsternberg** [comment]
Can you explain what you mean by this?

**Comment by dandv** [comment]
@jsternberg: I was looking for a Docker image that has influxd configured with HTTPS enabled. Would that be feasible using a self-signed certificate?

**Comment by jsternberg** [comment]
Hm, it might be worth putting a self-signed certificate in there for just sample images and we can configure it automatically. I don't think it's a good idea to enable it automatically, but I think it's reasonable to include this.

I think this is small enough it doesn't get in the way of proper usage and I think the workaround for this is sufficiently large enough that it's ok.

Not a high priority, but I'll put it on the list of things for me to do. Maybe for the 1.1 images.

**Comment by jsternberg** [comment]
To be clear, we would include the necessary files and the configuration in the image, but you would have to set an environment variable for it to use any of that stuff so those who are using this in a production setting would not even touch this change, but those who are using it for testing would be able to use the self-signed certificate.

**Comment by jsternberg** [comment]
I'm closing this because putting the self-signed certificate was causing too many security and usability concerns that it's not worth going into that minefield for something that can be easily resolved by the user.

Sorry.
