### ISSUE TITLE
config-directory

### ISSUE THREAD

**Issue by yufei** [influxdata/influxdata-docker#238]
if /etc/telegraf/telegraf.conf and a local setup /etc/telegraf/telegraf.d/local.conf both have a 
[[outputs.influxdb]] 

entry, then the docker image will not use the setup in local.conf, is that by default?

**Comment by danielnelson** [comment]
Sorry for the very late reply, actually both plugins should be used but you will need to make sure to load the container with `--config-directory /etc/telegraf/telegraf.d` to use the config directory.  Without this option only `/etc/telegraf/telegraf.conf` will be loaded.

We have an issue to add a default config directory in the telegraf repository: https://github.com/influxdata/telegraf/issues/5656

**Comment by Hipska** [comment]
If you still want this, please comment over at #568
