### ISSUE TITLE
2019-07-19T16:41:45Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, Undefined but requested input: docker_log

### ISSUE THREAD

**Issue by T-XCV** [influxdata/influxdata-docker#336]
added https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker_log

added the docker_logs input to my telegraf.conf following: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker_log

and I get the following error:

Creating telegraf ... done
Attaching to telegraf
telegraf    | 2019-07-19T16:41:45Z I! Starting Telegraf 1.9.5
telegraf    | 2019-07-19T16:41:45Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf    | 2019-07-19T16:41:45Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, Undefined but requested input: docker_log

is this input not available to the latest Telegraf image

**Comment by HTechHQ** [comment]
I have the same issue on 1.11.3

**Comment by jlsam** [comment]
I can confirm I also get the same error with `[[inputs.docker_log]]`.

I tried un-commenting all variables except TLS and filling in `container_name_include` and `container_state_include` although the comments imply empty is also accepted. The error is always present.

Another file with `[[inputs.docker]]` works as expected in the same machine.

**Comment by danielnelson** [comment]
As mentioned by @HTechHQ, you will need Telegraf 1.12.0 or later to use the docker_log plugin.
