### ISSUE TITLE
Missing link to documentation 1.0.2

### ISSUE THREAD

**Issue by manabuishii** [influxdata/influxdata-docker#36]
I use `influxdb:1.0.2-alpine`
1. I  access to  `Administrator interface` .
2. Click `Documentation` of upper menu.
3. Browser open https://docs.influxdata.com/influxdb/v1.0.2/introduction/getting_started/ but it is 404.

https://docs.influxdata.com/influxdb/v1.0/introduction/getting_started/
works fine.

**Comment by rossmcdonald** [comment]
Dupe of https://github.com/influxdata/influxdb/issues/7526
