### ISSUE TITLE
"core" buffer file in telegraf docker

### ISSUE THREAD

**Issue by ThomasBader** [influxdata/influxdata-docker#368]
I am running Telegraf as a docker on a Raspberry Pi 3.
The Telegraf docker is running with a memory limitation of 75 MiB.
Telegraf is sending system metrics to a InfluxDB, which is running as a web app.
If the InfluxDB is unvailable, then the wep app returns a 5XX http-response back to Telegraf.

My problem is that Telegraf starts to buffer the http put requests and sometimes saves the buffer directly in the root folder of the docker as a file named "core".

Is this a known behavior and is there an option to disable the creation of this "core"-file?

**Comment by danielnelson** [comment]
Telegraf doesn't save buffer contents to file ever, it is in-memory only.  Linux can be configured to write core files when a process crashes, these days more distros disable them by default but it is possible this is what is happening.

You could try doing the opposite of this if you want to disable:
https://packmad.github.io/enable-core-dumps-raspbian/

The best way to reduce memory usage is to lower the size the of the `metric_buffer_limit`, but I'd say that 75 MiB seems too restrictive.  This means you will lose metrics if InfluxDB is down very quickly.  You could set `metric_buffer_limit = 1000` and `metric_batch_size = 500`, this is about as low as you can go on these values practically, beyond this you could try to recompile without some of the plugins.

**Comment by ThomasBader** [comment]
Thanks for your answer.
I just checked for the core dump and it seems that it's activated on the Pi (even in the docker itself).
What would you see as an appropriate minimum value for memory limit if I set `metric_buffer_limit = 1000` and `metric_batch_size = 500`?

**Comment by danielnelson** [comment]
It's hard to say, maybe run it for a few minutes with InfluxDB down and check the max RSS and then add some headroom on that.
