### ISSUE TITLE
Create a docker container with plugin support

### ISSUE THREAD

**Issue by mildebrandt** [influxdata/influxdata-docker#369]
Create a docker container of telegraf that has plugin support. Enabling plugin support is outlined here: https://github.com/influxdata/telegraf/pull/6393

The plugin support in telegraf lets us include plugins without needing to compile our own version of telegraf. However, since a version of telegraf with plugin support isn't built as part of the official release process, we need to compile our own version of telegraf.

What we'd like to do is, create a docker container based on an officially released telegraf container and package our plugins and conf files along side.

**Comment by russorat** [comment]
@mildebrandt thanks for this request. I remember there were some unique requirements for the build process using Go plugins, so this might take some investigation to figure out.

**Comment by mildebrandt** [comment]
Thanks for looking into it. From the linked issue, I thought it was just adding the `goplugin` tag to the build command. I'll be attempting to build with that tag and writing external plugins...I'll be sure to post any issues I come across.

**Comment by mildebrandt** [comment]
I'm beginning to think there's no good way to support this with Go's limitations right now.

https://github.com/golang/go/issues/27751

https://github.com/golang/go/issues/26759

https://www.reddit.com/r/golang/comments/b6h8qq/is_anyone_actually_using_go_plugins/ejkxd2k/

**Comment by danielnelson** [comment]
I think for now let's close this issue and we can reevaluate if there are improvements to the plugin package in the future.
