### ISSUE TITLE
Arg to add custom tools

### ISSUE THREAD

**Issue by wuast94** [influxdata/influxdata-docker#370]
In another projekt i found that they add env variables to add custom pkg during install. 
In the dockerfile are args: 
```
ARG APT_PKGS
ARG CPAN_PKGS
ARG PIP_PKGS
ARG NPM_PKGS
```

And then the commands: 

```
apt-get install -qqy --no-install-recommends \
a \
b\
c\
${APT_PKGS}
```

and so on for the other. 

would be nice to see this too in telegraf for adding specific tools

**Comment by russorat** [comment]
@wuast94 thank you for opening this. We will investigate.

**Comment by danielnelson** [comment]
This is an interesting idea, but since the package needs rebuilt it seems that it isn't much of a saving over creating a new Dockerfile:

Untested, but something like this:
```
FROM telegraf:1.13.3

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends blah && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by wuast94** [comment]
you are half right. 
but maintaining an own dockerfile is not quite so nice. i need to edit this file .. build and start it and so on. 

with args i can use the official images and repos and thats the part were this thing gets quit intresting

im using unraid as host os and there i manage/backup/update all my containers over the web ui. when i set containers manually over command line/dockerfiles the system dont get rich of it and i have to manually backup thoose caontainers becouse backup scripts and so on dont get manually added containers. 

i hope you understand what i mean. adding an env over web ui or in docker-compose is a lot more easy than editing/managing self created dockerfiles

**Comment by danielnelson** [comment]
Maybe I misunderstood, I thought you were suggesting that we support build time variables.  Were you instead suggesting we run the apt-get commands at runtime as part of the ENTRYPOINT script?

**Comment by wuast94** [comment]
i think yes :) 

here you have an example. in the dockerfile you can see how they did it :) 

https://github.com/fhem/fhem-docker

**Comment by danielnelson** [comment]
It occurs to me that Docker has mechanisms for running a custom script in a container at startup.  All you need to do is mount a script into the container and specify it as an argument when you run the container, essentially the same as how you configure the telegraf.conf files.

**Comment by wuast94** [comment]
ok but then i have to make an script that installs the apps ? 
would be a solution but i think it is a lot easier to set an env and its done.

**Comment by wuast94** [comment]
![image](https://user-images.githubusercontent.com/16965460/74277175-57274780-4d17-11ea-9f8d-7b302d3d3ccb.png)
This is part of my config from the example linked above (fhem docker) 

i just enter tools i need inside the container and thats all. better then edit dockerfiles or make scripts and look that they get executed at start etc.

**Comment by danielnelson** [comment]
It would be easy for your case, but also not very flexible for others.  Can you share how you manage your telegraf.conf files?

**Comment by wuast94** [comment]
the good thing is that the most others dont have to use this. they even just can ignore the env and nothing should be changed for them. 

and people like me who wants to edit it can use the env and are flexible in installing packages. 

i just mount the telegraf.conf file into the container  /etc/telegraf/telegraf.conf

**Comment by danielnelson** [comment]
I think we probably shouldn't add this to the image.  For more complex setup scripts mounting a file into the container will work, and for the more simple case it can be specified when running the container:
```
docker run --rm -ti telegraf:latest /bin/bash -c 'apt-get update && apt-get install foo && telegraf'
```

**Comment by phillipjf** [comment]
@danielnelson any recommendations for achieving this without building a custom image on the latest images (At time of writing this is `1.21.4`)? The permissions on the `telegraf` user no longer allow this:

```sh
$ docker run -it 'telegraf:alpine' /bin/bash -c 'apk update && apk add ipmitool && telegraf'
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied

$ docker run -it 'telegraf' /bin/bash -c 'apt-get update && apt-get install ipmitool && telegraf'
Reading package lists... Done
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
```
