### ISSUE TITLE
Telegraf refusing to start due to invalid TOML syntax

### ISSUE THREAD

**Issue by hevos93** [influxdata/influxdata-docker#391]
This is the error i keep having:
[telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 1: invalid TOML syntax

I have done nothing to the config file, just generated it with:
docker run --rm telegraf telegraf config > telegraf.conf

And when i use this command to start:
docker run -d --name=telegraf  --net=influxdb -v $PWD/telegraf.conf:/etc/telegraf telegraf

It crashes, below is the complete error log:

2020-05-05T08:56:37Z I! Starting Telegraf 1.14.2

2020-05-05T08:56:37Z I! Using config file: /etc/telegraf/telegraf.conf

2020-05-05T08:56:37Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 1: invalid TOML syntax

This is my first time configuring influxdb and telegraf and i am completely lost.
Thanks in advance!

Config file: (it refused the .conf format so i converted it to txt)
[telegraf.txt](https://github.com/influxdata/influxdata-docker/files/4583771/telegraf.txt)

**Comment by danielnelson** [comment]
Can you attach the telegraf.conf file?

**Comment by hevos93** [comment]
The config file is now attached:)

**Comment by danielnelson** [comment]
Looks like the file is encoded as UTF-16, we have been wanting to add support for other text encodings but as of now only UTF-8 is supported.  Are you running the docker commands on Windows?

I think you will want to use your text editor to switch the type, or a utility program like `dos2unix`.

**Comment by hevos93** [comment]
Yes i am on Windows, but with linux containers. I used Notepad++ and changed the encoding to UTF-8 and it started! Now i just have to configure the rest.
Thanks!!
