### ISSUE TITLE
influxdb: admin defaults to false as of 1.1

### ISSUE THREAD

**Issue by tevjef** [influxdata/influxdata-docker#40]
With version 1.1 of Influxdb out and the deprecation of the admin panel, I believe the default config generated by `docker run --rm influxdb:1.1 influxd config` should also have the `[admin]` field `enabled` set to false.  Moreover, documentation referencing the admin panel on [Docker Hub](https://hub.docker.com/_/influxdb/) should be updated reflect the deprecation status of the panel.

**Comment by jsternberg** [comment]
I'm going to fix this, but it will only go into the 1.1.1 tag when we do that. I'm not going to update 1.1.0 with this at the moment since I don't like changing the behavior of a versioned image (even if the original behavior should have been something else).

That ok?

**Comment by tevjef** [comment]
That's good. Thanks for the quick reply!
