### ISSUE TITLE
Version 2.0 of InfluxDB is missing

### ISSUE THREAD

**Issue by ctron** [influxdata/influxdata-docker#441]
I looks like version 2.0 of InfluxDB is released for a while now, but this repository (and docker hub) only has version 1.8:

* https://www.influxdata.com/blog/influxdb-2-0-open-source-is-generally-available/
* https://hub.docker.com/_/influxdb
 
In the readme of the dockerhub page it says:

> In the future, the latest tag for this image will point to the latest released implementation of influxdb 2.0. This will happen when the first general available release for 2.0 exists.

In the blog post it says:

> Today, we are proud to announce that InfluxDB Open Source 2.0 is now generally available for everyone.

So I would say something is missing.

**Comment by Rid** [comment]
It seems that 2.0 docker hub images are imminent: https://github.com/influxdata/influxdb/issues/16649

**Comment by danxmoran** [comment]
2.0 is now available
