### ISSUE TITLE
no matching manifest for linux/arm/v7

### ISSUE THREAD

**Issue by Schnuecks** [influxdata/influxdata-docker#460]
since today if i pull influxdb:latest on my raspberry pi4 i got this error

`ERROR: no matching manifest for linux/arm/v7 in the manifest list entries`

**Comment by BudBundi** [comment]
See https://hub.docker.com/_/influxdb?tab=description

> latest updated to InfluxDB 2.x
> 
> The latest tag for this image now points to the latest released implementation of InfluxDB 2.x. If you are using the latest tag and would like to stay on the InfluxDB 1.x line, please update your environment to reference the 1.8 tag.

and

https://docs.influxdata.com/influxdb/v2.0/upgrade/v1-to-v2/

> InfluxDB 2.0 requires 64-bit operating systems.

I have the same problem. No arm 32 bit image.
Have to use influxdb:1.8 for now

**Comment by Schnuecks** [comment]
Thank you @BudBundi have set it to 1.8 and it worked.
