### ISSUE TITLE
Latest alpine version gives permission denied on startup

### ISSUE THREAD

**Issue by Ulrar** [influxdata/influxdata-docker#461]
Hi,

The latest image on the alpine tag does not start, always giving a permission denied on /var/lib/influxdb2 on startup.
I've tried deleting the volumes and starting from scratch but I always get the same error.

Downgrading to the previous image solves the issue (sha256:8b0668c31135a00187a237367bc867cc53e322931d676c7b19480f21232c7d01).

Thanks

**Comment by nickneutron** [comment]
Latest release broke my setup as well.  Grafana is no longer able to authenticate with the influxdb data source until i reverted as well.

My indluxdb doesn't have any credential assigned so it must be forcing one now.

t=2021-02-25T12:09:45-0800 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/2/query status=400 remote_addr=10.1.1.50 time_ms=1 size=36 referer="http://10.1.1.12:3000/d/EMeo02_mz/neutron-noc?orgId=1&refresh=60s"
t=2021-02-25T12:09:45-0800 lvl=info msg="Authentication to data source failed" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/3/query remote_addr=10.1.1.50 referer="http://10.1.1.12:3000/d/EMeo02_mz/neutron-noc?orgId=1&refresh=60s" body="{\"code\":\"unauthorized\",\"message\":\"Unauthorized\"}" statusCode=401

**Comment by Altycoder** [comment]
I have the same issue with grafana accessing influxdb and home assistant writing to it.  Home assistant now reports:

`2021-02-26 07:41:48 ERROR (SyncWorker_0) [homeassistant.components.influxdb] InfluxDB database is not accessible due to '401: {"code":"unauthorized","message":"Unauthorized"}'. Please check that the database, username and password are correct and that the specified user has the correct permissions set. Retrying in 60 seconds.`

The database does not have a username or password as as @nickneutron suggests something has changed wrt the authentication.

I'm using the influxdb:alpine image

**Comment by Ulrar** [comment]
This is actually not the same issue I'm having, mine does not start at all,
that looks like a different problem.
Interesting that it broke differently though, I do have authentication
enabled on mine, I wonder if it's related

**Comment by Altycoder** [comment]
Hmmm and rolling back to 2.0-alpine doesn't help either as I guess the changes made to the database are permanent.

My entire influx log:

`2021-02-26T08:13:12.	warn	boltdb not found at configured path, but DOCKER_INFLUXDB_INIT_MODE not specified, skipping setup wrapper	{"system": "docker", "bolt_path": ""},
ts=2021-02-26T08:13:15.749996Z lvl=info msg="Welcome to InfluxDB" log_id=0SZMECPG000 version=2.0.4 commit=4e7a59bb9a build_date=2021-02-08T17:47:02Z,
ts=2021-02-26T08:13:15.756188Z lvl=info msg="Resources opened" log_id=0SZMECPG000 service=bolt path=/var/lib/influxdb2/influxd.bolt,
ts=2021-02-26T08:13:15.758779Z lvl=info msg="Bringing up metadata migrations" log_id=0SZMECPG000 service=migrations migration_count=14,
ts=2021-02-26T08:13:16.038423Z lvl=info msg="Using data dir" log_id=0SZMECPG000 service=storage-engine service=store path=/var/lib/influxdb2/engine/data,
ts=2021-02-26T08:13:16.038568Z lvl=info msg="Compaction settings" log_id=0SZMECPG000 service=storage-engine service=store max_concurrent_compactions=2 throughput_bytes_per_second=50331648 throughput_bytes_per_second_burst=50331648,
ts=2021-02-26T08:13:16.038598Z lvl=info msg="Open store (start)" log_id=0SZMECPG000 service=storage-engine service=store op_name=tsdb_open op_event=start,
ts=2021-02-26T08:13:16.038696Z lvl=info msg="Open store (end)" log_id=0SZMECPG000 service=storage-engine service=store op_name=tsdb_open op_event=end op_elapsed=0.102ms,
ts=2021-02-26T08:13:16.038776Z lvl=info msg="Starting retention policy enforcement service" log_id=0SZMECPG000 service=retention check_interval=30m,
ts=2021-02-26T08:13:16.038914Z lvl=info msg="Starting precreation service" log_id=0SZMECPG000 service=shard-precreation check_interval=10m advance_period=30m,
ts=2021-02-26T08:13:16.039106Z lvl=info msg="Starting query controller" log_id=0SZMECPG000 service=storage-reads concurrency_quota=10 initial_memory_bytes_quota_per_query=9223372036854775807 memory_bytes_quota_per_query=9223372036854775807 max_memory_bytes=0 queue_size=10,
ts=2021-02-26T08:13:16.040306Z lvl=info msg="Configuring InfluxQL statement executor (zeros indicate unlimited)." log_id=0SZMECPG000 max_select_point=0 max_select_series=0 max_select_buckets=0,
ts=2021-02-26T08:13:16.346324Z lvl=info msg=Starting log_id=0SZMECPG000 service=telemetry interval=8h,
ts=2021-02-26T08:13:16.346365Z lvl=info msg=Listening log_id=0SZMECPG000 transport=http addr=:8086 port=8086,`

**Comment by danxmoran** [comment]
@Ulrar it shouldn't be related to authentication (auth is enabled by default in 2.x, there's no way to disable it).

As part of publishing 2.x, we switched to running commands as a non-root user. Depending on how your host system is configured, this can cause the permissions problems you're seeing.

Does passing `-u $(id -u):influxdb` to your `docker run` command make the error go away?

**Comment by danxmoran** [comment]
@nickneutron yes, auth is required in 2.x. If/when you try the upgrade again, you'll need to either:
1. Enable auth on your 1.x instance, create a user that can read your source DB(s), configure Grafana with the new user's auth, then upgrade the influxdb image (using the built-in upgrade triggers)
2. Upgrade the influxdb image (using the built-in upgrade triggers), use the `influx` CLI to create compatibility DBRP mapping(s) and auth, then configure Grafana with the new auth

If you haven't already seen it, check out the "Upgrading from InfluxDB 1.x" section of the [DockerHub docs](https://hub.docker.com/_/influxdb) for info on the upgrade support.

If you'd rather go with option 2, see our public docs for info on [creating DBRP mappings](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/v1/dbrp/create/) and [creating V1 auth tokens](https://docs.influxdata.com/influxdb/v2.0/reference/cli/influx/v1/auth/create/).

**Comment by danxmoran** [comment]
@Altycoder the relevant line from your logs is:
```
boltdb not found at configured path, but DOCKER_INFLUXDB_INIT_MODE not specified, skipping setup wrapper
```
To bootstrap your system on startup, you'll need to set some env vars. In the DockerHub docs, see "[Upgrading from InfluxDB 1.x](https://github.com/docker-library/docs/blob/master/influxdb/README.md#upgrading-from-influxdb-1x)" if you're upgrading an existing deployment, or "[Automated Setup](https://github.com/docker-library/docs/blob/master/influxdb/README.md#automated-setup)" for info on starting fresh

**Comment by Altycoder** [comment]
> @Altycoder the relevant line from your logs is:
> 
> ```
> boltdb not found at configured path, but DOCKER_INFLUXDB_INIT_MODE not specified, skipping setup wrapper
> ```
> 
> To bootstrap your system on startup, you'll need to set some env vars. In the DockerHub docs, see "[Upgrading from InfluxDB 1.x](https://github.com/docker-library/docs/blob/master/influxdb/README.md#upgrading-from-influxdb-1x)" if you're upgrading an existing deployment, or "[Automated Setup](https://github.com/docker-library/docs/blob/master/influxdb/README.md#automated-setup)" for info on starting fresh

Hi,

I was only a few days into my influxdb/grafana setup so I decided to start again from scratch starting with influxdb 2.x, I obviously chose a bad time to start right at the point of container migration from 1.x to 2.x.  No problem

**Comment by Ulrar** [comment]
> 
> 
> @Ulrar it shouldn't be related to authentication (auth is enabled by default in 2.x, there's no way to disable it).
> 
> As part of publishing 2.x, we switched to running commands as a non-root user. Depending on how your host system is configured, this can cause the permissions problems you're seeing.
> 
> Does passing `-u $(id -u):influxdb` to your `docker run` command make the error go away?

Hey,

That's it, I didn't like having it running as root so I had specified a -u myself. Guess when you started using a different uid in the image it didn't like that, removing it solves the issue. Thanks !
