### ISSUE TITLE
Instructions on Dockerhub is misleading - "latest" tag does not point to 2.* release

### ISSUE THREAD

**Issue by erkexzcx** [influxdata/influxdata-docker#463]
See: https://hub.docker.com/_/influxdb

It says:
> **The `latest` tag for this image now points to the latest released implementation of InfluxDB 2.x**. If you are using the `latest` tag and would like to stay on the InfluxDB 1.x line, please update your environment to reference the `1.8` tag.

Truth is - `latest` tag points to `1.*`, not `2.*` release.

**Comment by chrishoage** [comment]
![image](https://user-images.githubusercontent.com/1056886/109543616-62145d80-7a7b-11eb-8a1a-06b02fed85a7.png)

**Comment by danxmoran** [comment]
My guess is there was a small window where the docs got updated before the images were rebuilt. `latest` definitely got updated to `2.0` because we heard some surprised feedback from people who didn't see our notice 😅
