### ISSUE TITLE
How to login using CLI in a running container ? 

### ISSUE THREAD

**Issue by Jonarod** [influxdata/influxdata-docker#465]
As far as I know, in v1.7, after spawning new container I could:

```
docker exec -it my-influxdb-container influx -username user -password pass -host localhost -port 8086
```

Now in v2.0.4, this command actually prompts the `--help` options.

How do I provide login credentials to access influxdb using CLI now?

Thanks

**Comment by crl0wryjr** [comment]
You need to provide a Token that has the appropriate rights instead of password.
[https://docs.influxdata.com/influxdb/cloud/security/tokens/use-tokens/](url)

While I haven't tried it on the docker command line, I'm assuming you can set a variable and pass that.
If not you would substitute _-password_ <pass> with _-t <token>_

Hope this helps

**Comment by Jonarod** [comment]
Thanks for the reply but `-t` is not an option.
There are no flags available with `influx`, only specific commands exposed with `influx -h`.

**Comment by danxmoran** [comment]
@Jonarod nearly all of the commands do take a `-t` option for the auth token (the help text isn't as useful as it could be). The easiest way to set the total globally is probably to set the `INFLUX_TOKEN` env var when you spin up the container.

Did you upgrade from your 1.7 data using the container's built-in support? If so, the token should be persisted to a path within the container that the CLI knows to look at, and calls to `influx` should work without extra auth args.

Lastly (in case you haven't hit this yet), the 2.x `influx` CLI no longer has built-in REPL support. If you're trying to run queries against the DB you'll need to pass flux via stdin / a file to the `influx query` command.

**Comment by vivekmishra92** [comment]
when I'm on the Influx 2.0 version

Starting the container:

$ docker run --name=influxdb -d -p 8086:8086 influxdb

Run the influx client in this container:

$ docker exec -it influxdb influx
this command actually prompts the --help options.

what needs to done to access influxdb using CLI now?

**Comment by Jonarod** [comment]
According to @danxmoran the v1 CLI does not exist anymore. So I guess my question does not make sense anymore and we should pass queries using 

```
influx query -t <my_token> <my_query>
```

Just guessing, I did not try the above command.

I finally got back to 1.8.
