### ISSUE TITLE
Upgrade error rm: cannot remove '/var/lib/influxdb2/engine/wal/4d18dcaf0212e7bd/autogen/456': Directory not empty

### ISSUE THREAD

**Issue by dreamkiller52** [influxdata/influxdata-docker#471]
Hi, 
I encounter a few issues during the upgrade process of my influxdb docker 1.8 to 2.0.4

in the upgrade.log all is ok 

> {"level":"info","ts":1616033352.2994857,"caller":"upgrade/upgrade.go:395","msg":"Starting InfluxDB 1.x upgrade"}
> {"level":"info","ts":1616033352.2999074,"caller":"upgrade/upgrade.go:398","msg":"Upgrading config file","file":"/etc/influxdb/influxdb.conf"}
> {"level":"info","ts":1616033352.39868,"caller":"upgrade/upgrade.go:402","msg":"Config file upgraded.","1.x config":"/etc/influxdb/influxdb.conf","2.x config":"/etc/influxdb2/config.toml"}
> {"level":"info","ts":1616033352.3988657,"caller":"upgrade/upgrade.go:412","msg":"Upgrade source paths","meta":"/var/lib/influxdb/meta","data":"/var/lib/influxdb/data"}
> {"level":"info","ts":1616033352.3990054,"caller":"upgrade/upgrade.go:413","msg":"Upgrade target paths","bolt":"/var/lib/influxdb2/influxd.bolt","engine":"/var/lib/influxdb2/engine"}
> {"level":"info","ts":1616033352.5881813,"caller":"bolt/bbolt.go:76","msg":"Resources opened","service":"bolt","path":"/var/lib/influxdb2/influxd.bolt"}
> {"level":"info","ts":1616033352.6661072,"caller":"migration/migration.go:153","msg":"Bringing up metadata migrations","service":"migrations","migration_count":14}
> {"level":"info","ts":1616033362.1642268,"caller":"upgrade/setup.go:148","msg":"CLI config has been stored.","path":"/etc/influxdb2/influx-configs"}
> {"level":"info","ts":1616033362.164388,"caller":"upgrade/database.go:201","msg":"Checking available disk space"}
> {"level":"info","ts":1616033363.0342376,"caller":"upgrade/database.go:222","msg":"Computed disk space","free":"2.3 TB","required":"1.6 GB"}
> {"level":"info","ts":1616033363.0881262,"caller":"upgrade/database.go:51","msg":"Upgrading databases"}
> {"level":"warn","ts":1616033458.8931978,"caller":"upgrade/database.go:157","msg":"Empty retention policy"}
> {"level":"info","ts":1616033473.4203157,"caller":"upgrade/database.go:194","msg":"Database upgrade complete","upgraded_count":4}
> {"level":"info","ts":1616033473.4777935,"caller":"upgrade/security.go:30","msg":"There are no users in 1.x, nothing to upgrade"}
> {"level":"info","ts":1616033473.47907,"caller":"upgrade/upgrade.go:482","msg":"Upgrade successfully completed. Start the influxd service now, then log in","login_url":"http://localhost:8086"}

but the container crash with an exit code 1 and I have a lot of this line in my container log

> rm: cannot remove '/var/lib/influxdb2/engine/data/4d18dcaf0212e7bd/autogen/336/index/4': Directory not empty
> rm: cannot remove '/var/lib/influxdb2/engine/data/4d18dcaf0212e7bd/autogen/336/index/5': Directory not empty
> rm: cannot remove '/var/lib/influxdb2/engine/data/4d18dcaf0212e7bd/autogen/336/index/3': Directory not empty
> rm: cannot remove '/var/lib/influxdb2/engine/data/4d18dcaf0212e7bd/autogen/336/index/6': Directory not empty
> rm: cannot remove '/var/lib/influxdb2/engine/data/4d18dcaf0212e7bd/_series/06': Directory not empty
> rm: cannot remove '/var/lib/influxdb2/engine/data/4d18dcaf0212e7bd/_series/05': Directory not empty

When restarting the upgrade process restart and crash in the same way

**Comment by danxmoran** [comment]
@dreamkiller52 a few questions to help me debug:
1. What log/error do you see when the process crashes?
2. Do you see a log like "cleaning bolt and engine files to prevent conflicts on retry" anywhere?

**Comment by dreamkiller52** [comment]
1) I only have the directory not empty error I have no other log in the influxdb2 volume

2) Nothing like that , the only time i saw this line was when i have permission problem

**Comment by kareem613** [comment]
Same issue here. Here the final few logs of the upgrade process. 

```ts=2021-04-02T23:42:10.391227Z lvl=info msg="Opened shard" log_id=0THFEU3G000 service=storage-engine service=store op_name=tsdb_open index_version=tsi1 path=/var/lib/influxdb2/engine/data/ef4a64c497a5ef1a/autogen/2155 duration=73.324ms
ts=2021-04-02T23:42:10.442880Z lvl=info msg="index opened with 8 partitions" log_id=0THFEU3G000 service=storage-engine index=tsi
ts=2021-04-02T23:42:10.459792Z lvl=info msg="Opened file" log_id=0THFEU3G000 service=storage-engine engine=tsm1 service=filestore path=/var/lib/influxdb2/engine/data/ef4a64c497a5ef1a/autogen/2272/000000036-000000002.tsm id=0 duration=11.692ms
ts=2021-04-02T23:42:10.463610Z lvl=info msg="Reindexing TSM data" log_id=0THFEU3G000 service=storage-engine engine=tsm1 db_shard_id=2272
rm: cannot remove '/var/lib/influxdb2/engine/data/ef4a64c497a5ef1a/autogen': Directory not empty
```

After that the container exits with code 1.

**Comment by Phontana** [comment]
Same issue here. At the end of the upgrade, the container exits with a `Directory not empty` message.

**Comment by roqvist** [comment]
Same problem with 2.0.6, log attached.
I get the aforementioned `cleaning bolt and engine files to prevent conflicts` right before the spamming of the rm errors occur.

[influxdb2.log](https://github.com/influxdata/influxdata-docker/files/6488064/influxdb2.log)

**Comment by danxmoran** [comment]
@roqvist thank you so much for providing the full log, I think I see what's going on. After running automated upgrade, the entrypoint boots the server in prep for running any user-provided setup scripts. There's a ping-loop in the script that waits for the server to come up, and it looks like the loop is failing. I'm going to:
1. Bump the default value for the ping-loop to a much larger value
2. Allow the max timeout for the loop to be configured via env var
3. Fix the `rm` issue that's causing the unfortunate spamming
