### ISSUE TITLE
fails to create boltdb when docker volume points to a mounted network filesystem with restricted permissions

### ISSUE THREAD

**Issue by katbyte** [influxdata/influxdata-docker#473]
I'm having issues getting the docker container to initialize when using a volume that points to a cifs mounted filesystem with a "docker" user - i presume this is because the service isn't running as root and the UID/GID doesn't match (and when i use a local path it works just fine) and for some networked filesystems changing of permissions is not permitted - i've seen this with a number of other docker container/filesystems where chmod will not work. Two questions:

- is there a way to configure what uid/gid the service runs as?
- what UID/GID will it run as so i can use a dedicated mount for influx that has these permissions already?

docker compose and logs below:
```
  influx:
    image: influxdb:2.0.4-alpine
    container_name: influx
    hostname: influx
    restart: "no"
    user: "0"
    networks:
      web:
    ports:
      - "8086:8086"
    volumes:
      - /mnt/data/docker/metrics/influx/config:/etc/influxdb2
      - /mnt/data/docker/metrics/influx/data:/var/lib/influxdb2
      #- /home/docker/volumes/influx/config:/etc/influxdb2
      #- /home/docker/volumes/influx/data:/var/lib/influxdb2
    environment:
      - TZ="America/Vancouver"
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=kt
      - DOCKER_INFLUXDB_INIT_PASSWORD=pw
      - DOCKER_INFLUXDB_INIT_ORG=katbyte
      - DOCKER_INFLUXDB_INIT_BUCKET=katbyte
      - INFLUXDB_REPORTING_DISABLED=true
      - PUID=0
      - PGID=0
      - UID=0
      - GID=0
    labels:
      - traefik.enable=true
```

```
chmod: changing permissions of '/var/lib/influxdb2': Operation not permitted
chmod: changing permissions of '/var/lib/influxdb2/engine': Operation not permitted
chmod: changing permissions of '/etc/influxdb2': Operation not permitted
2021-03-23T23:35:51.759897076Z	info	booting influxd server in the background	{"system": "docker"}
2021-03-23T23:35:53.761517170Z	info	pinging influxd...	{"system": "docker"}
ts=2021-03-23T23:35:54.507424Z lvl=info msg="Welcome to InfluxDB" log_id=0T4MxyYl000 version=2.0.4 commit=4e7a59bb9a build_date=2021-02-08T17:47:02Z
Error: unable to open boltdb: open /var/lib/influxdb2/influxd.bolt: permission denied
See 'influxd -h' for help
ts=2021-03-23T23:35:54.510106Z lvl=error msg="Failed opening bolt" log_id=0T4MxyYl000 error="unable to open boltdb: open /var/lib/influxdb2/influxd.bolt: permission denied"
```

**Comment by danxmoran** [comment]
@katbyte you're correct, it's running up against our logic for running as a non-root user. The default UID/GID we set are both `1000`. When I've used `docker run` I've seen passing `-u $(id -u):influxdb` work to override the UID, but I'm not sure what the equivalent config would be in docker-compose.

**Comment by katbyte** [comment]
Well that explains some issues i noticed with pointing at a local volume, the files ended up owned by my login user as the first user created on a system is 1000.

I changed my compose file to include
```
  user: "1001:1001"
```

and it seems to work now with the shared mount! thanks 😃
