### ISSUE TITLE
Docker: nightly build for telegraf

### ISSUE THREAD

**Issue by Hipska** [influxdata/influxdata-docker#490]
## Overview

The telegraf team today produces nightly builds for the deb, rpm, and tar.gz downloads. It has come up a couple of times from customers as well as users asking for a nightly docker image to test the latest builds.

## Next Steps

- [ ] Work with Edge team to figure out how they used to publish images
- [ ] Create builds nightly
- [ ] Update Telegraf nightlies page with links to downloads
- [ ] Update Telegraf DockerHub docs with note about nightlies

## Expected Outcome

* Ability to get and use nightly docker images of Telegraf

**Comment by powersj** [comment]
Nightly builds are live and published to https://quay.io/repository/influxdb/telegraf-nightly?tab=tags

Nightly docs are updated here: https://github.com/influxdata/telegraf/blob/master/docs/NIGHTLIES.md
