### ISSUE TITLE
Docker container making lot of invalid DNS requests

### ISSUE THREAD

**Issue by DaveDavenport** [influxdata/influxdata-docker#505]
Might be a very silly question.

I am not sure where this comes from, but I am seeing lot of ( thousands and thousands a day) dns requests.
While tracing it back, it stops when I stop the influx docker image. I am running the `influxdb:1.8.4 image`.

The query is to a single address: `105e33538485.`

This kinda looks like a mac address. (but looking it up does not give a hint about manufacturer)

How can I figure out why this happens?  when does influx do a dns query?

**Comment by CalvinSchwartz** [comment]
I have the same Issue. My pihole log shows `cf92a21577d4` as a requested Domain which indeed is the Container Name of my **Kapacitor** Container. Influx and Kapacitor are running on the same bridge network therefore I guess Docker should answer this request but somehow it doesn't.

Settings:
- Kapacitor, Influx, Chronograf on the bridge network.
- Kapacitor URL: http://192.168.xxx.xx:9092 set in Chronograf
- Influx Version 1.8.4 on Raspberry Pi

Interesting is, that even after removing the connection to Kapacitor in Chronograf, stopping Kapacitor  and recreating the Influx as well as the Chronograf Container I still had multiple DNS request to `cf92a21577d4` per Minute.

@DaveDavenport You may want to edit the Title to "Docker container making lot of DNS requests to Kapacitor" or similar.

**Comment by DaveDavenport** [comment]
Don't have kapacitor running. (did have in the past)

**Comment by CalvinSchwartz** [comment]
If you had it in the past there's maybe a bug in InfluxDB which tries to access kapacitor even though it's no longer enabled?

**Comment by DaveDavenport** [comment]
wonder if it is a rule somewhere.. thanks for the hint, never made the connection to kapacitor

**Comment by CalvinSchwartz** [comment]
Setting the environment variable `KAPACITOR_HOSTNAME` for the Kapacitor container as well as setting `hostname` in the `/etc/kapacitor/kapacitor.conf` to the IP adress solved the issue partly.
See: [https://github.com/influxdata/kapacitor/issues/1647](https://github.com/influxdata/kapacitor/issues/1647)

**Comment by DaveDavenport** [comment]
hmm but I don't have a kapacitor container anymore.

**Comment by DaveDavenport** [comment]
Yep, there are many subscriptions towards that hostname.

**Comment by DaveDavenport** [comment]
Removing subscriptions fixed it.
