### ISSUE TITLE
kapacitor 1.6.x docker release

### ISSUE THREAD

**Issue by prashanthjbabu** [influxdata/influxdata-docker#506]
Is there an estimated timeline as to when kapacitor 1.6.x docker release would happen?

**Comment by prashanthjbabu** [comment]
@docmerlin any thoughts on this? specifically looking for 1.6.1 release

**Comment by docmerlin** [comment]
Very soon, I'm planning n putting in the PR for dockerhub tonight or tomorrow morning, but they have to approve it and merge it.

**Comment by prashanthjbabu** [comment]
@docmerlin I see that kapacitor 1.6.1 Dockerfiles are in via https://github.com/influxdata/influxdata-docker/pull/509 . When can we expect the kapacitor 1.6.1 images in docker hub?

**Comment by docmerlin** [comment]
@prashanthjbabu as soon as dockerhub merges my pr. :-)

**Comment by lesam** [comment]
1.6.2 is out already.
