### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by maxulm** [influxdata/influxdata-docker#520]
Hi,
since upgrading my telegraf-container from 1.8.3 to 1.9.x the connections cannot be established anymore.
The error ocurring is "no route to host".
I've already posted in Influxdataforum a few weaks ago, but my problem could not be solved.
Due to the fact that everything worked fine until the update, I guess there is a problem with the new version.

See my original post here:
[https://community.influxdata.com/t/no-route-to-host-since-upgraded-telegraf-to-1-19-x/20810](https://community.influxdata.com/t/no-route-to-host-since-upgraded-telegraf-to-1-19-x/20810)

**Comment by powersj** [comment]
Hi,

Sorry, no one commented here. It does look like you got things working so I am going to close this out.
