### ISSUE TITLE
[BUG] Kapacitor Image - Apline - 1.6.x - kapacitord: not found

### ISSUE THREAD

**Issue by kingsleyadam** [influxdata/influxdata-docker#523]
When I try to bring up an instance of `kapacitor:1.6.1-apline` or `kapacitor-1.6-alpine` The container crashes immediately I get the following output in the logs:

```
> docker logs -f 526abe4896ca
/entrypoint.sh: exec: line 11: kapacitord: not found
/entrypoint.sh: exec: line 11: kapacitord: not found
```

Running this on Ubuntu 20.04.2

```
> docker -v
Docker version 20.10.7, build f0df350
```

**Comment by lesam** [comment]
Kapacitor 1.6.2 is working properly.
