### ISSUE TITLE
Version 2.0.9: no manifest for linux/amd64

### ISSUE THREAD

**Issue by cailloumajor** [influxdata/influxdata-docker#531]
Pulling influxdb:2.0.9 on an x64 machine gives the following error:
```
2.0.9: Pulling from library/influxdb
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```
This is confirmed by looking at [this link to Docker Hub](https://hub.docker.com/_/influxdb?tab=tags&page=1&ordering=last_updated&name=2.0.9)
Screenshot below for the posterity:
![image](https://user-images.githubusercontent.com/8583146/135994187-eacb6346-3a52-4a19-a387-5f01446f809d.png)

**Comment by danxmoran** [comment]
@cailloumajor not sure what happened on the DockerHub side, I'll raise it with them

**Comment by danxmoran** [comment]
Ah, actually it's docker-library/official-images#11023

**Comment by cailloumajor** [comment]
docker-library/official-images#11023 is fixed. I tried pulling influxdb:2.0.9 for amd64, with success 🎉
