### ISSUE TITLE
monitoring docker containers not possible since telegraf:1.20.3

### ISSUE THREAD

**Issue by rguenther-dz** [influxdata/influxdata-docker#559]
since telegraf:1.20.3-alpine we get permission denied errors, if we try to monitor docker containers

root cause:
/var/run/docker.sock from the host needs to be accesed with root privileges.
since docker container telegraf:1.20.3, telegraf is not running as root anymore

**Comment by powersj** [comment]
Please see this blog post on the background for this change and what you can do to enable telegraf access to the socket:

https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/

**Comment by matthijskooijman** [comment]
I also ran into this. The current docker hub docs (https://hub.docker.com/_/telegraf) do currently suggest you can mount /var/lib/docker.sock into the container, but do not mention that additional setup is needed for the permissions.

Maybe those docs should be updated to also document the needed steps?

It would also be good to mention how to solve this on docker-compose, where it does not seem possible to do command substitution in the docker-compose.yml file (so I used `user: telegraf:112` to hardcode the docker gid, which isn't very pretty...).
