### ISSUE TITLE
CVE - Alpine docker image obsolete

### ISSUE THREAD

**Issue by macherel** [influxdata/influxdata-docker#564]
The alpine image is based on an old version of alpine.
Please update to alpine 3.15 to fix some busybox vulnerabilities

**Comment by powersj** [comment]
Is there a specific CVE fix you are after? I realize that there are new releases of the base image that get released periodically and we should keep images up to date. However, when I see an issue with CVE in it, I would prefer if you had a specific one you have seen needs to be fixed than to generically say fixes CVEs.

If you are scanning the images and found CVEs it would be great to see the output or to know how and what software you are using to scan images. And even better, contact us via security@influxdata.com if you find something.

Thanks!

**Comment by powersj** [comment]
FWIW I have merged #566 to update the Telegraf docker images. I'll leave this open for others to update the other container images.
