### ISSUE TITLE
Telegraf can't report smart_attributes when not run as root

### ISSUE THREAD

**Issue by strayer** [influxdata/influxdata-docker#571]
So, this is a bit weird to figure out… I noticed one of my servers was not reporting smart_attributes, but when I went into the container with `docker exec -it telegraf bash` and ran `telegraf --test` the attributes showed up. I realized that `exec`ing into the container will open a shell as root. When running `docker exec -u=telegraf -it telegraf bash` to get a shell in the container even `telegraf --test` isn't able to gather smart_attributes anymore.

This is how the server (Unraid) starts telegraf:

```
docker run --name='telegraf' \
  --net='host' \
  --privileged=true \
  -e TZ="Europe/Berlin" \
  -e HOST_OS="Unraid" \
  -e 'HOST_ETC'='/hostfs/etc' \
  -e 'HOST_PROC'='/hostfs/proc' \
  -e 'HOST_SYS'='/hostfs/sys' \
  -e 'HOST_VAR'='/hostfs/var' \
  -e 'HOST_RUN'='/hostfs/run' \
  -e 'HOST_MOUNT_PREFIX'='/hostfs' \
  -v '/mnt/user/appdata/telegraf/telegraf.conf':'/etc/telegraf/telegraf.conf':'ro' \
  -v '/':'/hostfs':'ro' \
  -v '/mnt/user/appdata/telegraf/host-stats.conf':'/etc/telegraf/telegraf.d/host-stats.conf':'ro' \
  -v '/mnt/user/appdata/telegraf/ping.conf':'/etc/telegraf/telegraf.d/ping.conf':'ro' \
  -v '/mnt/cache/appdata/telegraf/dns.conf':'/etc/telegraf/telegraf.d/dns.conf':'ro' \
  --hostname=redacted 'telegraf:latest' \
  --config-directory=/etc/telegraf/telegraf.d
```

```
# telegraf.conf
[global_tags]

[agent]
  interval = "60s"
  flush_interval = "60s"
  flush_jitter = "0s"
  logtarget = "stderr"

[[outputs.influxdb]]
  urls = ["https://example.tld"]
  database = "foobar"
  skip_database_creation = true

  username = "foo"
  password = "bar"

# host-stats.conf
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs", "nsfs"]

[[inputs.net]]
  interfaces = ["eth0", "eth0.8", "eth1"]

[[inputs.diskio]]
[[inputs.linux_sysctl_fs]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.temp]]
[[inputs.netstat]]
[[inputs.nstat]]
[[inputs.interrupts]]
[[inputs.internal]]

[[inputs.smart]]
  path_smartctl = "/hostfs/usr/sbin/smartctl"
  path_nvme = "/hostfs/usr/sbin/nvme"
  #enable_extensions = ["auto-on"]
  #nocheck = "standby"
  #read_method = "concurrent"
  attributes = true
  timeout = "30s"

# ping.conf
[[inputs.ping]]
  method = "native"
  urls = [
    "heise.de",
    "8.8.8.8",
    "8.8.4.4",
    "1.1.1.1",
    "1.0.0.1",
    "2606:4700:4700::1111",
    "2606:4700:4700::1001",
    "www.example.com.global.prod.fastly.net",
    "s3.us-east-1.amazonaws.com",
    "s3.us-west-1.amazonaws.com",
    "s3.eu-central-1.amazonaws.com"
  ]

# dns.conf
[[inputs.dns_query]]
  servers = [
    "1.1.1.1",
    "8.8.8.8",
  ]
```

When overriding the entrypoint with `--entrypoint=''` (forcing telegraf to run as root) the smart_attribute metrics show up.

I'm note sure if this is a telegraf bug or something related to the user/binary capabilities.

**Comment by powersj** [comment]
Hi,

Thanks for the taking the time to file an issue.

I believe what are you seeing is expected as `smartctl` does require root-level permissions to collect data successfully. Since the default was changed to running telegraf as the telegraf user and not as root, then you will have to modify your configuration, as you have determined, to successfully run `smartctl`.

I am going to go ahead and close as working as expected, but if you do think something else is up feel free to add more here.

Thanks!

**Comment by powersj** [comment]
The entry point method is actually a new way I have not seen used before.

In previous issues, the primary concern was adding a group to the user is to modify the groups the user is part of via the CLI by adding one of the following:

```
--group-add $(getent group | awk -F ":" '{ if($1 == "docker") print $3 }')
```

```
--user telegraf:$(stat -c '%g' /var/run/docker.sock)
```

In your case, you need to run as root, so I try adding the following to the startup CLI:

```
--user root
```
