### ISSUE TITLE
Pod keeps on crashing due to entrypoint.sh 

### ISSUE THREAD

**Issue by samkhamk** [influxdata/influxdata-docker#601]
Hello Team,

I am trying to use telegraf for the first time and it seems Pod keeps on crashing due to entrypoint.sh 

pod keeps restarting after below logs  
+ set -e
+ '[' '' = - ']'
+ '[' 10001 -ne 0 ']'
+ exec 
can you please let me know what needs to be done to get this resolved, I am using 1.22 version.

Regards,
SAM

**Comment by powersj** [comment]
Hi,

Can you please provide the actual error message that you are seeing? And either `docker info` or information on what K8s platform you are using.

I would also suggest heading over to our [Community Slack](https://influxdata.com/slack) or[ Community Page](https://community.influxdata.com/), where we have a lot of talented community members there who could help answer your questions and get you going quickly.

Thanks

**Comment by samkhamk** [comment]
Hello @powersj,

Thank you , but just now I have  figured out that I need to pass Telegraf after entry point script in my customize startup script.
`**./entrypoint.sh telegraf**' where I have mentioed `**entrypoint.sh**' in my startup script.

Its working fine , now I am exploring how I can collect stats of other pods. Thanks for your time and support :)

Regards,
SAM
