### ISSUE TITLE
Chronograf 1.10 docker image

### ISSUE THREAD

**Issue by R290** [influxdata/influxdata-docker#641]
I'd like to upgrade from 1.9.4. to 1.10 but the docker image is not available. I was going to open a pull request but it seems that https://dl.influxdata.com/chronograf/releases/chronograf_1.10.0_amd64.deb.asc does not exist. I get the following contents:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>chronograf/releases/chronograf_1.10.0_amd64.deb.asc</Key><RequestId>V4GQWC29YN99Y34C</RequestId><HostId>eDjYI2Gt+h5vmS+ZQsP4b61r39sih939U2XiBdecR67Yiiow6MQF7eJz39gX5unmnGPQOPlFisM=</HostId></Error>
```

This causes the gpg verify to fail.

**Comment by powersj** [comment]
@bnpfeife is this something you could look at?

**Comment by bnpfeife** [comment]
@R290 Thanks for catching this. It appears that the signatures were not uploaded for Chronograf 1.10.0. I've uploaded the signatures so the packages should now verify.

**Comment by R290** [comment]
@bnpfeife could you also add 1.10 to the manifest at https://github.com/docker-library/official-images/blob/master/library/chronograf?
