### ISSUE TITLE
podman - setpriv: failed to execute telegraf: Operation not permitted

### ISSUE THREAD

**Issue by deags** [influxdata/influxdata-docker#646]
With the latest build from docker.io and executing like this:

`[root@hostname ~]# podman run --name=test4 telegraf:latest
setpriv: failed to execute telegraf: Operation not permitted`

I have been unable to troubleshoot this further. influxdb runs fine starting in my usual way which gives me the same error as this.

Thanks

**Comment by powersj** [comment]
Hi,

I was able to reproduce:

```
root@j-vm:~# podman version
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
root@j-vm:~# podman run --name=test4 docker.io/library/telegraf:latest
Trying to pull docker.io/library/telegraf:latest...
Getting image source signatures
Copying blob de4a4c6caea8 [======================================] 4.9MiB / 4.9MiB
Copying blob e425edf5c582 done  
Copying blob 2b698d0487ff done  
Copying blob 17c9e6141fdb done  
Copying blob 351dbe0337c2 done  
Copying blob 4edced8587e6 done  
Copying blob e66348ab089a done  
Copying config 7f17768c61 done  
Writing manifest to image destination
Storing signatures
setpriv: failed to execute telegraf: Operation not permitted
```

Doing some searching I came across [this article](https://www.redhat.com/sysadmin/container-permission-denied-errors) which says a couple of things:

First, try with `--privileged`, which works for me so based on that article it is something with privileges is the problem.

```
podman run --privileged docker.io/library/telegraf:latest
```

If I run the following to avoid the entrypoint it also works:

```
podman run --entrypoint=telegraf docker.io/library/telegraf:latest
```

That narrows it down to two things from the entrypoint:

a) setting the capabilities
b) the launching of the binary

To test setting the capabilities I ran the following and telegraf started right up:

```
podman run --cap-add cap_net_raw docker.io/library/telegraf:latest
```

From that article it sounds like the `cap_net_raw` capability is not included. It looks like [others](https://williamlieurance.com/telegraf-podman-cap-net-raw/) have come across this as well. I think this is something we need to add to the docs, so I'll leave this open till that is done.
