### ISSUE TITLE
InfluxDB 2.5.0 alpine image is still on 2.4.0

### ISSUE THREAD

**Issue by prevosti** [influxdata/influxdata-docker#651]
The recently released 2.5.0 alpine docker images are still on the 2.4.0 version.

In the Dockerfile the following two env vars are still set to 2.4.0:
```
ENV INFLUXDB_VERSION 2.4.0

ENV INFLUX_CLI_VERSION 2.4.0
```

**Comment by bnpfeife** [comment]
Hey, thanks for reporting this. It looks like it was fixed in https://github.com/influxdata/influxdata-docker/commit/dbda26c3fc16b4c94854bba48632d1d6997673ed.
