### ISSUE TITLE
(Docker container) extra ":" added to "http-bind-address" configuration value

### ISSUE THREAD

**Issue by MarcelOnaga** [influxdata/influxdata-docker#661]
Running a Docker container build on arm64v8/influxdb:2.6  
with a config file that contains:  
`http-bind-address = "http://myaddress:8086"`  

container failse with:
```
ts=2022-12-23T19:43:12.956816Z lvl=error msg="Failed to set up TCP listener" log_id=0ex80p4W000 service=tcp-listener addr=http://myaddress:8086 error="listen tcp: address http://myaddress:8086: too many colons in address"
```   

on `https://github.com/influxdata/influxdata-docker/blob/master/influxdb/2.6/entrypoint.sh`

**Comment by bnpfeife** [comment]
(Reopening in case that doesn't solve the problem.)

**Comment by bnpfeife** [comment]
As I haven't heard anything and am 99% sure the aforementioned issue is the problem, I am closing this issue.
