### ISSUE TITLE
Alpine-based Kapacitor image misses ca-certificates

### ISSUE THREAD

**Issue by mkuzmin** [influxdata/influxdata-docker#72]
Docker image `kapacitor:1.2.0-alpine` misses root certificates.
This causes at least two issues:

- Slack integration does not work: 
```
kapacitor_1  | [dc21423b-346d-49cb-bf62-6742606507bc:alert3] 2017/03/19 13:35:20 E! failed to send event to Slack Post https://hooks.slack.com/services/<ID>: x509: failed to load system roots and no roots provided
```

- Usage reports are not sent:
```
[reporting] 2017/03/19 13:35:04 E! error while sending usage report on startup: Post https://usage.influxdata.com/api/v1/usage/kapacitor: x509: failed to load system roots and no roots provided
```

Debian-based image works fine.

**Comment by jsternberg** [comment]
@mkuzmin can you try out the kapacitor images in #74 to make sure that works? It should keep the ca-certificates package installed instead of uninstalling it now.
