### ISSUE TITLE
kapacitor: missing documentation for backwards incompatible change to running kapacitor as non-root in v1.7.4

### ISSUE THREAD

**Issue by andoks** [influxdata/influxdata-docker#754]
After upgrading the kapacitor docker image from v1.7.0 to v1.7.4 we started getting consistent errors during startup: `run: open server: open service *storage.Service: open boltdb @ "/var/lib/kapacitor/kapacitor.db": open /var/lib/kapacitor/kapacitor.db: permission denied` and kapacitor refused to start.

After some digging I found commit 4adc1daa632a7f79b4cb386216e74154e1a5bf13 that changed the docker image to run kapacitor as a non-root user between v1.7.3 and v1.7.4, and the ability continue running kapacitor as root by setting KAPACITOR_AS_ROOT=true.

Should this perhaps be documented in the docs over at https://hub.docker.com/_/kapacitor?

**Comment by powersj** [comment]
Thanks for calling this out: https://github.com/docker-library/docs/pull/2450
