### ISSUE TITLE
Add /etc/nsswitch.conf to alpine images

### ISSUE THREAD

**Issue by 2solt** [influxdata/influxdata-docker#76]
Looks like non of the TICK application using /etc/hosts without it.
Adding the following line to Dockerfile solves the problem:
```RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' > /etc/nsswitch.conf```

**Comment by jsternberg** [comment]
It looks like the default value for this in the standard ubuntu image is:

```
hosts: files dns
```

What are the other sections you've placed in the line?

**Comment by 2solt** [comment]
Yeah your right, that's should be sufficient.
(The other options is for mDNS or Multicast DNS )
