### ISSUE TITLE
Chronograf 1.0.0-beta

### ISSUE THREAD

**Issue by blaggacao** [influxdata/influxdata-docker#8]
@jsternberg What's the matter with chronograf 1.0.0-beta3?
I was trying to build a rancher catalogue item with the newest 1.0.0 builds and surprise, for chronograf, there isn't. :smile:

**Comment by blaggacao** [comment]
It's getting worse, no alpine builds?? :disappointed:

**Comment by jsternberg** [comment]
@blaggacao sorry, there are currently no alpine builds available for Chronograf at the moment as we don't build a version compatible with alpine yet. We also have not released a beta for the 1.0 version of Chronograf at the moment. Please use the 0.13 version for now.
