### ISSUE TITLE
Chronograf docker image not working

### ISSUE THREAD

**Issue by mlmarius** [influxdata/influxdata-docker#92]
today, 2017-05-15 I have installed the 'chronograf' image. The app is failing and I am seeing some errors in my javascript console:

```
Uncaught ReferenceError: __WEBPACK_AMD_DEFINE_ARRAY__ is not defined jquery.js:10180
Uncaught ReferenceError: Dygraph is not defined dygraph-combined.js:5
XHR finished loading: "http://*****/chronograf.css". clipper.js:3
```

**Comment by goller** [comment]
Hi @mlmarius, I'm trying to reproduce your error now.  Are you using `chronograf:1.3.0` ?   Also, could you try chronograf when your browser is in incognito mode?

**Comment by mlmarius** [comment]
I have tried in both incognito mode on both chrome and firefox ( older versions ). Anyway it did work properly once i tried to access it from another computer so i guess this was my computer's problem. Sorry for the trouble.
