### ISSUE TITLE
Data does not persist between chronograf docker container restarts

### ISSUE THREAD

**Issue by deweller** [influxdata/influxdata-docker#97]
I have mounted a host directory to `/var/lib/chronograf` in the container.

When I restart the container, my dashboard data disappears.  Furthermore, there is nothing in the mounted directory on the host.

Is /var/lib/chronograf used or did the location of the persistent data change in the container?

I'm using `chronograf:1.3-alpine`.

**Comment by deweller** [comment]
I was able to workaround this by setting the `BOLT_PATH` environment variable to "/var/lib/chronograf/chronograf-v1-.db".

Was the default changed?

**Comment by mcfedr** [comment]
Seems the default wasnt set, and the file is stored as `/chronograf-v1.db`

I'm having this issue using the non alpine image

**Comment by goller** [comment]
Hi @deweller , @mcfedr, thanks for writing in!

The workaround to set `BOLT_PATH`  to `/var/lib/chronograf` and mount a host directory to `/var/lib/chronograf` is the way to do this now.

I'm thinking changing the default `BOLT_PATH` to `/var/lib/chronograf` is the way to go.  What do you think?

**Comment by deweller** [comment]
Changing the `BOLT_PATH` default to `/var/lib/chronograf` makes sense to me.  That would be consistent with the docker image documentation.

**Comment by mcfedr** [comment]
Definitely the way to go. Especially as the documentation would suggest
that's the case already, and all the other influx images are similarly setup

**Comment by n0madic** [comment]
Since by default the chronograf creates a BoltDB base in the current directory, you just need to add it to the Dockerfile:
`WORKDIR /var/lib/chronograf`

**Comment by jsternberg** [comment]
@goller does the environment variable or the command line option take priority? I would say add it as an environment variable if the command line option takes priority and add it as a command line option if the environment variable takes priority (lowest priority is where we want to put it).

We'll have a fix for this uploaded by tomorrow. For now, just set the `BOLT_PATH` environment variable manually.
